require 'spec_helper'

# In these exercises, follow the pattern done in the example exercise
# where you create a method in the relevant model
# and pass in any arguments relevant to the current exercise
# all SQL queries generated by this test are printed to log for your convenience

describe 'SQL Exercises' do

  it "finds the total movies made by Spielberg" do
    Sequel.total_by('Steven Spielberg').should eq 3
  end

  it "finds the total movies made by Jackson" do
    Sequel.total_by('Peter Jackson').should eq 2
  end

  before(:each) do
    @logger = ActiveRecord::Base.logger
    ActiveRecord::Base.logger = Logger.new(STDOUT)
  end

  after(:each) do
    ActiveRecord::Base.logger = @logger
  end
end